library(shinycssloaders)
library(dplyr)

StartDate = as.character(Sys.Date()-365*4)
EndDate = as.character(Sys.Date())

#------------------------------------------------------------------------
# Define UI layout and navigation bars
#------------------------------------------------------------------------

navbarPage(title = 'Stock Analytics',
           theme = 'cerulean',
           tabPanel('Select Stocks',
                    sidebarLayout(
                      sidebarPanel(
                        textInput("s1", label = strong("Input Stock_1 Symbol:"),
                                  value = "PNC"),
                        textInput("s2", label = strong("Input Stock_2 Symbol:"),
                                  value = "HBAN"),
                        textInput("s3", label = strong("Input Stock_3 Symbol:"),
                                  value = "BAC"),
                        # Select date range to be plotted
                        dateRangeInput("date", strong("Select Date Range:"), start = StartDate, end = EndDate,
                                       min = StartDate, max = EndDate
                        ),
                        # Include clarifying text ----
                        helpText('After entering stock symbols above please
                                 \nclick the button below to run the 
                                 \nthe application'),
                        actionButton("go", "Pull Data"),
                        width = 3
                      ),
                      # generate plot on the page
                      mainPanel(
                        p('Price trend of the selected securities over time.'),
                        plotOutput(outputId = "line") %>% withSpinner(),
                        p('The chart below depicts the performance of a $1 
invested in each security
                          \nin the past and its growth generated by holding it over
                          time.'),
                        plotOutput(outputId = 'fv') %>% withSpinner(),
                        tags$a(href = "https://finance.yahoo.com/trending-tickers",
                               "Source: Yahoo Finance",
                               target = "_blank"),
                        width = 8
                      )
                    )
           ),
           tabPanel(
             'About',
             h4('Stock Analytics Application'),
             p('This application is mainly to outline my skill with the
R Statiscal Programming language
               \nand is prepared solely for informational purposes, and is not an
               \noffer to buy or sell or a solicitation of an offer to buy or sell
               \nany security, product, service or investment. The opinions expressed in this application
               \ndo not constitute investment advice and independent advice
               should be sought where appropriate.'),
             p('For more information about this app please contact me at:
             \ncourtneywilliams561@gmail.com'
                    )
           )
             )