library(shinycssloaders)
library(shinythemes)
library(dplyr)

StartDate = as.character(Sys.Date()-365*4)
EndDate = as.character(Sys.Date())

#------------------------------------------------------------------------
# Define UI layout and navigation bars
#------------------------------------------------------------------------

navbarPage(
  theme = shinytheme('cerulean'),
  title = 'Stock Analytics',
           tabPanel('Select Stocks',
                    icon = icon('search'),
                    sidebarLayout(
                      sidebarPanel(
                        # include directions...
                        helpText('Type in ticker symbols in the boxes
                                 below then press the Pull Data button:'),
                        textInput("s1", label = strong("Input Stock_1 Symbol:"),
                                  value = "PNC"),
                        textInput("s2", label = strong("Input Stock_2 Symbol:"),
                                  value = "HBAN"),
                        textInput("s3", label = strong("Input Stock_3 Symbol:"),
                                  value = "BAC"),
                        # Select date range to be plotted
                        dateInput(
                          inputId = 'StartDate',
                          label = strong('Enter Start Date:'),
                          value = StartDate
                        ),
                        dateInput(
                          inputId = 'EndDate',
                          label = strong('Enter End Date:'),
                          value = EndDate
                        ),
                        # Include clarifying text ----
                        helpText('After entering stock symbols above please
                                 click the button below to run the 
                                 the application'),
                        actionButton("go", "Pull Data"),
                        width = 3
                      ),
                      # generate plot on the page
                      mainPanel(
                        p('Price trend of the selected securities over time.'),
                        plotOutput(outputId = "line") %>% withSpinner(),
                        tags$a(href = "https://finance.yahoo.com/trending-tickers",
                               "Source: Yahoo Finance",
                               target = "_blank"),
                        width = 8
                      )
                    )
           ),
  tabPanel(
    'Analytics',
    icon = icon('bar-chart-o'),
    sidebarLayout(
      sidebarPanel(
        helpText('The graphs depict varying views of the
                 secuirites'),
        width = 3
      ),
      mainPanel(
        p('The chart below depicts the performance of a $1 
invested in each security
          in the past and its growth generated by holding it over
          time.'),
        plotOutput(outputId = 'fv') %>% withSpinner(),
        p('Correlation plot of the returns 
                 for the chosen securities.'),
        plotOutput(outputId = 'corr') %>% withSpinner(),
        width = 8
      )
    )
    
  ),
           tabPanel(
             'About',
             icon = icon('book'),
             h4('Stock Analytics Application'),
             p('This application is mainly to outline my skill with the
R Statiscal Programming language
               and is prepared solely for informational purposes, and is not an
               offer to buy or sell or a solicitation of an offer to buy or sell
               any security, product, service or investment. The opinions expressed in this application
               do not constitute investment advice and independent advice
               should be sought where appropriate.'),
             p('For more information about this app please contact me at:
             courtneywilliams561@gmail.com'
                    )
           )
             )